language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - cd productivity.py
  - pip install pytest
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

script: pytest

jobs:
  include:
    - stage: deploy
      python: "3.9"
      script:
        - git config --global user.name "semantic-release (via TravisCI)"
        - git config --global user.email "semantic-release@travis"
        - pip install python-semantic-release
        - echo $TRAVIS_PULL_REQUEST
        - echo $TRAVIS_BRANCH
        # python-semantic-release installs version of importlib-metadata
        # that is too old for twine
        - pip install -U importlib-metadata
        - semantic-release -v Info publish
